name: Build Release APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Generate Android Files
        run: flutter create --platforms=android --org com.vmateindia.priceapk .

      - name: Set Minimum SDK 21
        run: |
          echo "flutter.minSdkVersion=21" >> android/local.properties

      - name: Restore Firebase Config
        run: |
          if [ -f "google-services.json" ]; then
            cp google-services.json android/app/
          fi

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
